pumukitadmin_broadcast_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: pumukitadmin.controller.broadcast:indexAction
        _sylius:
            filterable: true

pumukitadmin_broadcast_create:
    pattern: /create
    methods: [GET, POST]
    defaults:
        _controller: pumukitadmin.controller.broadcast:createAction
        _sylius:
            redirect: pumukitadmin_broadcast_index

pumukitadmin_broadcast_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitadmin.controller.broadcast:updateAction
        _sylius:
            redirect: pumukitadmin_broadcast_index

pumukitadmin_broadcast_batch_delete:
    pattern: /delete
    methods: [DELETE]
    defaults:
        _controller: pumukitadmin.controller.broadcast:batchDeleteAction
        _sylius:
            redirect: pumukitadmin_broadcast_index

pumukitadmin_broadcast_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: pumukitadmin.controller.broadcast:deleteAction
        _sylius:
            redirect: pumukitadmin_broadcast_index

pumukitadmin_broadcast_copy:
    pattern: /{id}/copy
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitadmin.controller.broadcast:copyAction
        _sylius:
            redirect: pumukitadmin_broadcast_index

pumukitadmin_broadcast_show:
    pattern: /{id}
    methods: [GET]
    defaults:
        _controller: pumukitadmin.controller.broadcast:showAction

pumukitadmin_broadcast_default:
    pattern: /{id}/default
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitadmin.controller.broadcast:defaultAction
        _sylius:
            redirect: pumukitadmin_broadcast_index
