pumukitadmin_event_index:
    pattern: /
    methods: [GET, POST]
    defaults:
        _controller: pumukitadmin.controller.event:indexAction
        _sylius:
            filterable: true

pumukitadmin_event_create:
    pattern: /create
    methods: [GET, POST]
    defaults:
        _controller: pumukitadmin.controller.event:createAction
        _sylius:
            redirect: pumukitadmin_event_index

pumukitadmin_event_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitadmin.controller.event:updateAction
        _sylius:
            redirect: pumukitadmin_event_index

pumukitadmin_event_batch_delete:
    pattern: /delete
    methods: [DELETE]
    defaults:
        _controller: pumukitadmin.controller.event:batchDeleteAction
        _sylius:
            redirect: pumukitadmin_event_index

pumukitadmin_event_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: pumukitadmin.controller.event:deleteAction
        _sylius:
            redirect: pumukitadmin_event_index

pumukitadmin_event_show:
    pattern: /{id}
    methods: [GET]
    defaults:
        _controller: pumukitadmin.controller.event:showAction
