pumukitadmin_link_create:
    pattern: /create/{id}
    methods: [GET, POST]
    defaults:
        _controller: pumukitadmin.controller.link:createAction

pumukitadmin_link_update:
    pattern: /{id}/update/{mmId}
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitadmin.controller.link:updateAction

pumukitadmin_link_delete:
    pattern: /{id}/delete/{mmId}
    methods: [DELETE]
    defaults:
        _controller: pumukitadmin.controller.link:deleteAction

pumukitadmin_link_up:
    pattern: /{id}/up/{mmId}
    methods: [POST]
    defaults:
        _controller: pumukitadmin.controller.link:upAction

pumukitadmin_link_down:
    pattern: /{id}/down/{mmId}
    methods: [POST]
    defaults:
        _controller: pumukitadmin.controller.link:downAction
