pumukitadmin_material_create:
    pattern: /create/{id}
    methods: [GET, POST]
    defaults:
        _controller: pumukitadmin.controller.material:createAction

pumukitadmin_material_update:
    pattern: /{id}/update/{mmId}
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitadmin.controller.material:updateAction

pumukitadmin_material_upload:
    pattern: /{id}/upload
    methods: [GET, POST]
    defaults:
        _controller: pumukitadmin.controller.material:uploadAction

pumukitadmin_material_delete:
    pattern: /{id}/delete/{mmId}
    methods: [DELETE]
    defaults:
        _controller: pumukitadmin.controller.material:deleteAction

pumukitadmin_material_up:
    pattern: /{id}/up/{mmId}
    methods: [POST]
    defaults:
        _controller: pumukitadmin.controller.material:upAction

pumukitadmin_material_down:
    pattern: /{id}/down/{mmId}
    methods: [POST]
    defaults:
        _controller: pumukitadmin.controller.material:downAction

pumukitadmin_material_list:
    pattern: /{id}/list
    methods: [GET, POST]
    defaults:
        _controller: pumukitadmin.controller.material:listAction