pumukitadmin_mms_index:
    pattern: /series
    methods: [GET]
    defaults:
        _controller: pumukitadmin.controller.mms:indexAction
        _sylius:
            filterable: true

pumukitadmin_mms_create:
    pattern: /{id}/create
    methods: [GET, POST]
    defaults:
        _controller: pumukitadmin.controller.mms:createAction
        _sylius:
            redirect: pumukitadmin_mms_index

pumukitadmin_mms_edit:
    pattern: /{id}/edit
    methods: [GET]
    defaults:
        _controller: pumukitadmin.controller.mms:editAction

pumukitadmin_mms_update_meta:
    pattern: /{id}/update/meta
    methods: [POST]
    defaults:
        _controller: pumukitadmin.controller.mms:updatemetaAction

pumukitadmin_mms_update_pub:
    pattern: /{id}/update/pub
    methods: [POST]
    defaults:
        _controller: pumukitadmin.controller.mms:updatepubAction

pumukitadmin_mms_batch_delete:
    pattern: /delete
    methods: [DELETE]
    defaults:
        _controller: pumukitadmin.controller.mms:batchDeleteAction
        _sylius:
            redirect: pumukitadmin_mms_index

pumukitadmin_mms_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: pumukitadmin.controller.mms:deleteAction
        _sylius:
            redirect: pumukitadmin_mms_index

pumukitadmin_mms_copy:
    pattern: /{id}/copy
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitadmin.controller.mms:copyAction
        _sylius:
            redirect: pumukitadmin_mms_index

pumukitadmin_mms_show:
    pattern: /{id}/show
    methods: [GET, POST]
    defaults:
        _controller: pumukitadmin.controller.mms:showAction

pumukitadmin_mms_up:
    pattern: /{id}/up
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitadmin.controller.mms:upAction
        _sylius:
            redirect: pumukitadmin_mms_index

pumukitadmin_mms_down:
    pattern: /{id}/down
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitadmin.controller.mms:downAction
        _sylius:
            redirect: pumukitadmin_mms_index

pumukitadmin_mms_top:
    pattern: /{id}/top
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitadmin.controller.mms:topAction
        _sylius:
            redirect: pumukitadmin_mms_index

pumukitadmin_mms_bottom:
    pattern: /{id}/bottom
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitadmin.controller.mms:bottomAction
        _sylius:
            redirect: pumukitadmin_mms_index

pumukitadmin_mms_addtag:
    pattern: /{id}/addtag/
    methods: [POST]
    defaults:
        _controller: pumukitadmin.controller.mms:addTagAction
        _sylius:
            redirect: pumukitadmin_mms_edit

pumukitadmin_mms_deletetag:
    pattern: /{id}/deletetag/{tagId}
    methods: [DELETE]
    defaults:
        _controller: pumukitadmin.controller.mms:deleteTagAction

pumukitadmin_mms_getchildrentag:
    pattern: /{id}/getchildrentag/
    methods: [GET]
    defaults:
        _controller: pumukitadmin.controller.mms:getChildrenTagAction
