pumukitadmin_person_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: pumukitadmin.controller.person:indexAction
        _sylius:
            filterable: true

pumukitadmin_person_create:
    pattern: /create
    methods: [GET, POST]
    defaults:
        _controller: pumukitadmin.controller.person:createAction
        _sylius:
            redirect: pumukitadmin_person_index

pumukitadmin_person_update:
    pattern: /{id}/update
    methods: [GET, POST]
    defaults:
        _controller: pumukitadmin.controller.person:updateAction

pumukitadmin_person_batch_delete:
    pattern: /delete
    methods: [DELETE]
    defaults:
        _controller: pumukitadmin.controller.person:batchDeleteAction
        _sylius:
            redirect: pumukitadmin_person_index

pumukitadmin_person_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: pumukitadmin.controller.person:deleteAction
        _sylius:
            redirect: pumukitadmin_person_index

pumukitadmin_person_copy:
    pattern: /{id}/copy
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitadmin.controller.person:copyAction
        _sylius:
            redirect: pumukitadmin_person_index

pumukitadmin_person_show:
    pattern: /{id}/show
    methods: [GET]
    defaults:
        _controller: pumukitadmin.controller.person:showAction

pumukitadmin_person_up:
    pattern: /{id}/{roleId}/{mmId}/up
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitadmin.controller.person:upAction
        _sylius:
            redirect: pumukitadmin_person_index

pumukitadmin_person_down:
    pattern: /{id}/{roleId}/{mmId}/down
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitadmin.controller.person:downAction
        _sylius:
            redirect: pumukitadmin_person_index

pumukitadmin_person_list_autocomplete:
    pattern: /{mmId}/{roleId}/listautocomplete
    methods: [GET]
    defaults:
        _controller: pumukitadmin.controller.person:listAutocompleteAction

pumukitadmin_person_list:
    pattern: /list
    methods: [GET, POST]
    defaults:
        _controller: pumukitadmin.controller.person:listAction

pumukitadmin_person_create_relation:
    pattern: /{mmId}/{roleId}/createrelation
    methods: [GET, POST]
    defaults:
        _controller: pumukitadmin.controller.person:createRelationAction

pumukitadmin_person_update_relation:
    pattern: /{id}/{roleId}/{mmId}/updaterelation
    methods: [GET, POST]
    defaults:
        _controller: pumukitadmin.controller.person:updateRelationAction

pumukitadmin_person_delete_relation:
    pattern: /{id}/{roleId}/{mmId}/delete_relation
    methods: [POST, DELETE]
    defaults:
        _controller: pumukitadmin.controller.person:deleteRelationAction

pumukitadmin_person_link:
    pattern: /{mmId}/{roleId}/{id}/link
    methods: [GET, POST]
    defaults:
        _controller: pumukitadmin.controller.person:linkAction

pumukitadmin_person_auto_complete:
    pattern: /autocomplete
    methods: [GET, POST]
    defaults:
        _controller: pumukitadmin.controller.person:autoCompleteAction