pumukitadmin_role_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: pumukitadmin.controller.role:indexAction
        _sylius:
            filterable: true
            sorting:
                rank: desc

pumukitadmin_role_create:
    pattern: /create
    methods: [GET, POST]
    defaults:
        _controller: pumukitadmin.controller.role:createAction
        _sylius:
            redirect: pumukitadmin_role_index

pumukitadmin_role_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitadmin.controller.role:updateAction
        _sylius:
            redirect: pumukitadmin_role_index

pumukitadmin_role_batch_delete:
    pattern: /delete
    methods: [DELETE]
    defaults:
        _controller: pumukitadmin.controller.role:batchDeleteAction
        _sylius:
            redirect: pumukitadmin_role_index

pumukitadmin_role_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: pumukitadmin.controller.role:deleteAction
        _sylius:
            redirect: pumukitadmin_role_index

pumukitadmin_role_copy:
    pattern: /{id}/copy
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitadmin.controller.role:copyAction
        _sylius:
            redirect: pumukitadmin_role_index

pumukitadmin_role_up:
    pattern: /{id}/up
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitadmin.controller.role:upAction
        _sylius:
            redirect: pumukitadmin_role_index

pumukitadmin_role_down:
    pattern: /{id}/down
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitadmin.controller.role:downAction
        _sylius:
            redirect: pumukitadmin_role_index

pumukitadmin_role_top:
    pattern: /{id}/top
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitadmin.controller.role:topAction
        _sylius:
            redirect: pumukitadmin_role_index

pumukitadmin_role_bottom:
    pattern: /{id}/bottom
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitadmin.controller.role:bottomAction
        _sylius:
            redirect: pumukitadmin_role_index
