pumukitadmin_series_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: pumukitadmin.controller.series:indexAction
        _sylius:
            filterable: true

pumukitadmin_series_create:
    pattern: /create
    methods: [GET, POST]
    defaults:
        _controller: pumukitadmin.controller.series:createAction
        _sylius:
            redirect: pumukitadmin_series_index

pumukitadmin_series_update:
    pattern: /{id}/update
    methods: [GET, POST, DELETE]
    defaults:
        _controller: pumukitadmin.controller.series:updateAction

pumukitadmin_series_batch_delete:
    pattern: /delete
    methods: [DELETE]
    defaults:
        _controller: pumukitadmin.controller.series:batchDeleteAction
        _sylius:
            redirect: pumukitadmin_series_index

pumukitadmin_series_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: pumukitadmin.controller.series:deleteAction
        _sylius:
            redirect: pumukitadmin_series_index

pumukitadmin_series_copy:
    pattern: /{id}/copy
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitadmin.controller.series:copyAction
        _sylius:
            redirect: pumukitadmin_series_index

pumukitadmin_series_show:
    pattern: /{id}/show
    methods: [GET]
    defaults:
        _controller: pumukitadmin.controller.series:showAction
