pumukitadmin_user_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: pumukitadmin.controller.user:indexAction
        _sylius:
            filterable: true

pumukitadmin_user_create:
    pattern: /create
    methods: [GET, POST]
    defaults:
        _controller: pumukitadmin.controller.user:createAction
        _sylius:
            redirect: pumukitadmin_user_index

pumukitadmin_user_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitadmin.controller.user:updateAction
        _sylius:
            redirect: pumukitadmin_user_index

pumukitadmin_user_batch_delete:
    pattern: /delete
    methods: [DELETE]
    defaults:
        _controller: pumukitadmin.controller.user:batchDeleteAction
        _sylius:
            redirect: pumukitadmin_user_index

pumukitadmin_user_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: pumukitadmin.controller.user:deleteAction
        _sylius:
            redirect: pumukitadmin_user_index
