pumukitadmin_fos_user:
    resource: @PumukitAdminBundle/Resources/config/routes/fos_user.yml

pumukit_direct:
    resource: "@PumukitAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

pumukitadmin_user:
    resource: @PumukitAdminBundle/Resources/config/routes/user.yml
    prefix: /admin/user

pumukitadmin_direct:
    resource: @PumukitAdminBundle/Resources/config/routes/direct.yml
    prefix: /admin/direct

pumukitadmin_event:
    resource: @PumukitAdminBundle/Resources/config/routes/event.yml
    prefix: /admin/event

pumukitadmin_role:
    resource: @PumukitAdminBundle/Resources/config/routes/role.yml
    prefix: /admin/role

pumukitadmin_broadcast:
    resource: @PumukitAdminBundle/Resources/config/routes/broadcast.yml
    prefix: /admin/broadcast

pumukitadmin_series:
    resource: @PumukitAdminBundle/Resources/config/routes/series.yml
    prefix: /admin/series

pumukitadmin_tag:
    resource: @PumukitAdminBundle/Resources/config/routes/tag.yml
    prefix: /admin/tag

pumukitadmin_seriespic:
    resource: @PumukitAdminBundle/Resources/config/routes/seriespic.yml
    prefix: /admin/seriespic

pumukitadmin_mms:
    resource: @PumukitAdminBundle/Resources/config/routes/mms.yml
    prefix: /admin/mms

pumukitadmin_person:
    resource: @PumukitAdminBundle/Resources/config/routes/person.yml
    prefix: /admin/person

pumukitadmin_mmtemplate:
    resource: @PumukitAdminBundle/Resources/config/routes/mmtemplate.yml
    prefix: /admin/mmtemplate

pumukitadmin_mmspic:
    resource: @PumukitAdminBundle/Resources/config/routes/mmspic.yml
    prefix: /admin/mmspic

pumukitadmin_link:
    resource: @PumukitAdminBundle/Resources/config/routes/link.yml
    prefix: /admin/link

pumukitadmin_material:
    resource: @PumukitAdminBundle/Resources/config/routes/material.yml
    prefix: /admin/material

pumukitadmin_track:
    resource: @PumukitAdminBundle/Resources/config/routes/track.yml
    prefix: /admin/track